"use client";
import { useEffect,useMemo,useRef,useState } from "react";

type Doc={id:string;title:string;content:string;updatedAt:string};
type Folder={id:string;title:string;open:boolean;docs:Doc[];children:Folder[]};
type Notebook={id:string;title:string;description:string;accent:string;folders:Folder[]};
const seed:Notebook[]=[{id:"welcome",title:"欢迎使用",description:"SQLite 笔记本",accent:"#4d6b52",folders:[{id:"start",title:"开始",open:true,children:[],docs:[{id:"hello",title:"开始使用",updatedAt:"刚刚",content:"# 开始使用\n\n支持 **Markdown**、表格、公式、代码和 Mermaid 图表。\n\n| 功能 | 状态 |\n| --- | --- |\n| SQLite | 已启用 |\n\n$$E = mc^2$$\n\n```mermaid\ngraph LR\n A[写作] --> B[发布]\n```"}]}]}];
const docsOf=(fs:Folder[]):Doc[]=>fs.flatMap(f=>[...f.docs,...docsOf(f.children||[])]);
const mapFolders=(fs:Folder[],fn:(f:Folder)=>Folder):Folder[]=>fs.map(f=>fn({...f,children:mapFolders(f.children||[],fn)}));
const updateFolder=(fs:Folder[],id:string,fn:(f:Folder)=>Folder):Folder[]=>fs.map(f=>f.id===id?fn(f):({...f,children:updateFolder(f.children||[],id,fn)}));
const removeDoc=(fs:Folder[],id:string):[Folder[],Doc|undefined]=>{let found:Doc|undefined;const next=fs.map(f=>{const hit=f.docs.find(d=>d.id===id);if(hit)found=hit;const[c,ch]=removeDoc(f.children||[],id);if(ch)found=ch;return{...f,docs:f.docs.filter(d=>d.id!==id),children:c}});return[next,found]};
const removeFolder=(fs:Folder[],id:string):[Folder[],Folder|undefined]=>{let found:Folder|undefined;const next:Folder[]=[];for(const f of fs){if(f.id===id){found=f;continue}const[c,hit]=removeFolder(f.children||[],id);if(hit)found=hit;next.push({...f,children:c})}return[next,found]};
const folderContains=(f:Folder,id:string):boolean=>f.id===id||(f.children||[]).some(c=>folderContains(c,id));
const folderOf=(fs:Folder[],id:string):Folder|undefined=>{for(const f of fs){if(f.docs.some(d=>d.id===id))return f;const x=folderOf(f.children||[],id);if(x)return x}};
const folderOfId=(fs:Folder[],id:string):Folder|undefined=>{for(const f of fs){if(f.id===id)return f;const x=folderOfId(f.children||[],id);if(x)return x}};
function renderMD(md:string){const esc=(s:string)=>s.replace(/&/g,"&amp;").replace(/</g,"&lt;");let out="",code=false,lang="",buf="";const inline=(s:string)=>esc(s).replace(/!\[([^\]]*)\]\(([^)]+)\)/g,'<img src="$2" alt="$1">').replace(/\$([^$]+)\$/g,'<span class="math">$1</span>').replace(/\*\*(.+?)\*\*/g,"<strong>$1</strong>").replace(/`(.+?)`/g,"<code>$1</code>");for(const line of md.split("\n")){if(line.startsWith("```")){if(!code){code=true;lang=line.slice(3);buf=""}else{out+=`<pre class="${lang==="mermaid"?"diagram":""}"><b>${lang==="mermaid"?"Mermaid 图表":lang}</b><code>${esc(buf)}</code></pre>`;code=false}continue}if(code){buf+=line+"\n";continue}if(/^\|.+\|$/.test(line)&&!/^\|[- :|]+\|$/.test(line)){out+=`<table><tr>${line.slice(1,-1).split("|").map(x=>`<td>${inline(x.trim())}</td>`).join("")}</tr></table>`;continue}if(line.startsWith("# "))out+=`<h1>${inline(line.slice(2))}</h1>`;else if(line.startsWith("## "))out+=`<h2>${inline(line.slice(3))}</h2>`;else if(line.startsWith("> "))out+=`<blockquote>${inline(line.slice(2))}</blockquote>`;else if(line.startsWith("- "))out+=`<li>${inline(line.slice(2))}</li>`;else if(line.trim())out+=`<p>${inline(line)}</p>`}return out}

export default function Home(){
 const[books,setBooks]=useState<Notebook[]>(seed),[bookId,setBookId]=useState(seed[0].id),[docId,setDocId]=useState("hello"),[raw,setRaw]=useState(false),[saved,setSaved]=useState(true),[notice,setNotice]=useState(""),[query,setQuery]=useState(""),[deploySidebar,setDeploySidebar]=useState(true);
 const[drag,setDrag]=useState<{kind:"doc"|"folder";id:string;parent?:string}|null>(null),[dropTarget,setDropTarget]=useState<string|null>(null);const importRef=useRef<HTMLInputElement>(null),imageRef=useRef<HTMLInputElement>(null);
 const book=books.find(b=>b.id===bookId)||books[0],doc=docsOf(book?.folders||[]).find(d=>d.id===docId)||docsOf(book?.folders||[])[0];
 useEffect(()=>{fetch("/api/notebooks").then(r=>r.json()).then((x:Notebook[])=>{if(x.length){setBooks(x);setBookId(x[0].id);setDocId(docsOf(x[0].folders)[0]?.id)}}).catch(()=>{})},[]);
 const change=(content:string)=>{setSaved(false);setBooks(bs=>bs.map(b=>({...b,folders:mapFolders(b.folders,f=>({...f,docs:f.docs.map(d=>d.id===docId?{...d,content,updatedAt:"刚刚"}:d)}))})))};
 const save=async()=>{await fetch("/api/notebooks",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(books)});setSaved(true);toast("已保存到 SQLite")};
 const toast=(s:string)=>{setNotice(s);setTimeout(()=>setNotice(""),2600)};
 const addFolder=(parent?:string)=>{const f:Folder={id:crypto.randomUUID(),title:"新建目录",open:true,docs:[],children:[]};setBooks(bs=>bs.map(b=>b.id!==bookId?b:{...b,folders:parent?updateFolder(b.folders,parent,x=>({...x,children:[...x.children,f]})):[...b.folders,f]}))};
 const addDoc=(folder:string)=>{const id=crypto.randomUUID();setBooks(bs=>bs.map(b=>b.id!==bookId?b:{...b,folders:updateFolder(b.folders,folder,f=>({...f,docs:[...f.docs,{id,title:"未命名文档",content:"# 未命名文档\n\n开始写作…",updatedAt:"刚刚"}]}))}));setDocId(id)};
 const move=(to?:string)=>{if(!drag)return;setBooks(bs=>bs.map(b=>{if(b.id!==bookId)return b;if(drag.kind==="doc"){if(!to)return b;const[fs,d]=removeDoc(b.folders,drag.id);return d?{...b,folders:updateFolder(fs,to,f=>({...f,open:true,docs:[...f.docs,d]}))}:b}const source=folderOfId(b.folders,drag.id);if(!source||to===drag.id||(to&&folderContains(source,to)))return b;const[fs,moved]=removeFolder(b.folders,drag.id);if(!moved)return b;return{...b,folders:to?updateFolder(fs,to,f=>({...f,open:true,children:[...f.children,moved]})):[...fs,moved]}}));setSaved(false);setDrag(null);setDropTarget(null)};
 const insert=(s:string)=>{if(doc)change(doc.content+"\n\n"+s);setRaw(true)};
 const upload=async(f?:File)=>{if(!f)return;const fd=new FormData();fd.append("file",f);const r=await fetch("/api/upload",{method:"POST",body:fd});const x=await r.json();insert(`![${f.name}](${x.url})`);toast("图片已上传并插入")};
 const importFiles=async(fl:FileList|null)=>{if(!fl)return;const fd=new FormData();fd.append("notebookId",bookId);Array.from(fl).forEach(f=>{const path=(f as File&{webkitRelativePath?:string}).webkitRelativePath||f.name;fd.append("files",f);fd.append("paths",path)});const r=await fetch("/api/import",{method:"POST",body:fd}),x=await r.json();const fresh=await fetch("/api/notebooks").then(v=>v.json());setBooks(fresh);toast(`已导入 ${x.imported||0} 个文件`)};
 const share=async()=>{if(!doc)return;await save();const r=await fetch("/api/share",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({documentId:doc.id})}),x=await r.json();if(!r.ok){toast("生成分享链接失败");return}const url=new URL(x.url,location.origin).toString();try{await navigator.clipboard.writeText(url);toast(`分享链接已复制：${x.id}`)}catch{window.prompt("复制分享链接",url)}};
 const filtered=useMemo(()=>mapFolders(book.folders,f=>({...f,docs:f.docs.filter(d=>d.title.toLowerCase().includes(query.toLowerCase()))})),[book,query]);
 const tree=(fs:Folder[],depth=0):React.ReactNode=>fs.map(f=><div className={`folder ${dropTarget===f.id?"drop-target":""}`} key={f.id} style={{paddingLeft:depth*9}} onDragEnter={e=>{e.preventDefault();e.stopPropagation();setDropTarget(f.id)}} onDragOver={e=>{e.preventDefault();e.stopPropagation()}} onDragLeave={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node))setDropTarget(null)}} onDrop={e=>{e.preventDefault();e.stopPropagation();move(f.id)}}><button draggable className="folder-row" onDragStart={e=>{e.stopPropagation();setDrag({kind:"folder",id:f.id})}} onClick={()=>setBooks(bs=>bs.map(b=>b.id!==bookId?b:{...b,folders:updateFolder(b.folders,f.id,x=>({...x,open:!x.open}))}))}><span className="folder-handle">⠿</span><span>{f.open?"⌄":"›"}</span><b>□</b>{f.title}<em>{docsOf([f]).length}</em><i onClick={e=>{e.stopPropagation();addFolder(f.id)}}>＋</i></button>{f.open&&<><div className="docs">{f.docs.map(d=><button key={d.id} draggable onDragStart={e=>{e.stopPropagation();setDrag({kind:"doc",id:d.id,parent:f.id})}} className={d.id===docId?"active":""} onClick={()=>setDocId(d.id)}><span>≡</span><div><b>{d.title}</b><small>{d.updatedAt}</small></div></button>)}</div>{tree(f.children||[],depth+1)}</>}</div>);
 return <main className="app-shell"><aside className="rail"><div className="brand">M</div><button className="rail-btn active">▤</button><button className="rail-btn">⌕</button><div className="rail-space"/><button className="rail-btn">⚙</button><div className="avatar">若</div></aside><aside className="sidebar"><div className="side-head"><div><span className="eyebrow">SQLITE 工作空间</span><h2>我的笔记</h2></div><button className="icon-button">＋</button></div><div className="book-switch">{books.map(b=><button key={b.id} className={b.id===bookId?"selected":""} onClick={()=>{setBookId(b.id);setDocId(docsOf(b.folders)[0]?.id)}}><i style={{background:b.accent}}/>{b.title}<span>{docsOf(b.folders).length}</span></button>)}</div><div className="side-rule"/><div className={`tree-title ${dropTarget==="root"?"drop-root":""}`} onDragOver={e=>{e.preventDefault();setDropTarget("root")}} onDrop={e=>{e.preventDefault();move()}}><span>多级目录 · 拖到这里移至根级</span><div><button title="新建目录" onClick={()=>addFolder()}>□＋</button><button title="新建文档" onClick={()=>book.folders[0]&&addDoc(book.folders[0].id)}>＋</button></div></div><div className="search-wrap">⌕<input className="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索当前笔记…"/></div><div className="tree">{tree(filtered)}</div><div className="side-foot"><span>◉</span><div><b>{saved?"SQLite 已同步":"有未保存更改"}</b><small>data/mdocman.db</small></div></div></aside>
 <section className="workspace"><header className="topbar"><div className="crumb"><span>{book.title}</span><b>/</b><span>{folderOf(book.folders,docId)?.title}</span><b>/</b><strong>{doc?.title}</strong></div><div className="top-actions"><input ref={importRef} hidden multiple type="file" accept=".md" {...({webkitdirectory:""} as object)} onChange={e=>importFiles(e.target.files)}/><button className="ghost" onClick={()=>importRef.current?.click()}>导入目录</button><a className="ghost export" href={`/api/export?notebookId=${bookId}`}>导出 ZIP</a><button className="ghost" onClick={share}>分享链接</button><label className="sidebar-option"><input type="checkbox" checked={deploySidebar} onChange={e=>setDeploySidebar(e.target.checked)}/>发布含目录</label><span className={saved?"status saved":"status"}>● {saved?"已保存":"编辑中"}</span><button className="ghost" onClick={save}>保存</button><button className="publish" onClick={async()=>{const r=await fetch("/api/build",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({includeSidebar:deploySidebar})}),x=await r.json();toast(`增量生成完成：更新 ${x.changed||0}，删除 ${x.removed||0}`)}}>一键发布 ↗</button></div></header>
 <div className="toolbar"><div><button onClick={()=>insert("## 新标题")}>H2</button><button onClick={()=>insert("**粗体文字**")}><b>B</b></button><button onClick={()=>insert("```go\nfmt.Println(\"Hello\")\n```")}>{`<>`}</button><button title="表格" onClick={()=>insert("| 列一 | 列二 |\n| --- | --- |\n| 内容 | 内容 |")}>▦</button><button title="数学公式" onClick={()=>insert("$$\nE = mc^2\n$$")}>∑</button><button title="Mermaid 图表" onClick={()=>insert("```mermaid\ngraph LR\n A[开始] --> B[完成]\n```")}>◇</button><input ref={imageRef} hidden type="file" accept="image/*" onChange={e=>upload(e.target.files?.[0])}/><button title="上传图片" onClick={()=>imageRef.current?.click()}>▧</button></div><button className={raw?"mode active":"mode"} onClick={()=>setRaw(!raw)}>{raw?"渲染预览":"Markdown"}</button></div>
 {doc&&<div className="paper"><input className="doc-title" value={doc.title} onChange={e=>setBooks(bs=>bs.map(b=>({...b,folders:mapFolders(b.folders,f=>({...f,docs:f.docs.map(d=>d.id===doc.id?{...d,title:e.target.value}:d)}))})))}/><div className="doc-meta"><span>{book.title}</span><i/>最后编辑于 {doc.updatedAt}<i/>{doc.content.length} 字</div>{raw?<textarea className="raw-editor" value={doc.content} onChange={e=>change(e.target.value)}/>:<div className="editor preview" dangerouslySetInnerHTML={{__html:renderMD(doc.content)}}/>}</div>}<footer className="bottom"><span>SQLite</span><span>UTF-8</span><span>Markdown + GFM</span><i/><span>{saved?"同步完成":"等待保存"}</span></footer></section>{notice&&<div className="toast">✓ {notice}</div>}</main>
}
